repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v0.942"
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: ["pandera"]
  #       args: [--ignore-missing-imports, --disallow-untyped-defs]
  #       exclude: "conf.py|__main__.py|(test_*.py)"
